### ISSUE TITLE
EPG files not working and showing 404.

### ISSUE THREAD

**Issue by Reenagrg100** [iptv-org/api#10]
Hi,

We are referring the following file: https://iptv-org.github.io/api/guides.json for getting the program's data from the URLs mentioned there in this file and looking at the URLs it looks like the links has been made private.
For eg: https://iptv-org.github.io/epg/guides/en/mtel.ba.json

Is there any way to access this data?

**Comment by freearhey** [comment]
> Is there any way to access this data?

No, access to these files is currently restricted to everyone.

More details: https://github.com/iptv-org/iptv-org.github.io/issues/9#issuecomment-1430887905
