### ISSUE TITLE
Is there going to be a fix for the iptv removal?

### ISSUE THREAD

**Issue by 03stevensmi** [iptv-org/api#11]
I need the counties & category m3u for the latest iptv.org list.

is this going to be fixed and usable again?

In the mean time, Is there any way you could provide me with the latest 
countries & categories m3u list 
with the EPG if possible please?

Cheers! ;D

**Comment by freearhey** [comment]
https://github.com/orgs/iptv-org/discussions/12#discussioncomment-5019786

**Comment by 03stevensmi** [comment]
> just found that, you beat me to it. Thanks.
