### ISSUE TITLE
The streams Json is missing content

### ISSUE THREAD

**Issue by Buhos-Dev** [iptv-org/api#16]
In the Json that returns https://iptv-org.github.io/api/streams.json you should put the url of the image of the transmitted channel and the name of the channel that is transmitted, it would be more comfortable for everyone to have that information in that API, thanks!

**Comment by freearhey** [comment]
You can already get all this information from https://iptv-org.github.io/api/channels.json by channel ID.

More details: https://github.com/iptv-org/api#channels

**Comment by Buhos-Dev** [comment]
The API https://iptv-org.github.io/api/channels.json does not have the streaming url, the ideal would be to have a single Json with all the information

**Comment by xemles** [comment]
How often is the streams.json updated? I can see a bunch of japanese streams being removed 5 days ago, but that are still on the streams.json
