### ISSUE TITLE
channel is empty

### ISSUE THREAD

**Issue by Sangamvideo** [iptv-org/api#20]
https://iptv-org.github.io/api/streams.json. 

response 
{
        "channel": "",
        "url": "http://ott-cdn.ucom.am/s9/index.m3u8",
        "timeshift": null,
        "http_referrer": null,
        "user_agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 12_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML,like Gecko) Mobile/15E148"
    },
    
    in this response channel is empty

**Comment by LondonX** [comment]
That is strange, I got this issue just yesterday (about 14hrs ago), before this issue appears, I got one channel which has no `url`, not even `""` or `null`, and that make my App crashing.

**Comment by LondonX** [comment]
I notice that not all streams in json are channel empty, but a lot indeed.
In my case I ignored all the streams without channel, and filtered out all the channels without stream.

**Comment by freearhey** [comment]
Closed in favor of https://github.com/orgs/iptv-org/discussions/1811
