### ISSUE TITLE
This application, IPTV Mine, is an M3U streaming player that uses the iptv-org API for fetching and displaying channel playlists

### ISSUE THREAD

**Issue by DrFiles** [iptv-org/api#25]
This application, IPTV Mine, is an M3U streaming player that uses the iptv-org API for fetching and displaying channel playlists. It is important to note the following: 
The app's source code is available on GitHub: [IPTV Mine GitHub Repository](https://github.com/samyak2403/IPTVmine).:

**Comment by freearhey** [comment]
If you want the link to this app to be seen by the rest of the community, it is better to publish it here instead: https://github.com/iptv-org/awesome-iptv
