### ISSUE TITLE
"channel":null

### ISSUE THREAD

**Issue by mpbejo** [iptv-org/api#7]
Hi everybody,
I see when I perform a https://iptv-org.github.io/api/streams.json
there are thousand of "channel":null but I think all the channels should be have a name and a corrispondence with "id" on channels.json.
Is it correct or I don't understand how the API works
Thank You 
Best Regards
Marco

**Comment by freearhey** [comment]
Hello,
The thing is that we take channel IDs directly from [iptv-org/iptv](https://github.com/iptv-org/iptv) where not all streams are still labeled (https://github.com/iptv-org/iptv/milestone/1). 
So until this is done we have nothing to do but leave "channel" empty
