### ISSUE TITLE
Request to add country in streams API

### ISSUE THREAD

**Issue by Deadlineem** [iptv-org/api#8]
Streams json api outputs:

`{"channel":"1001Noites.br","url":"https://cdn.jmvstream.com/w/LVW-8155/ngrp:LVW8155_41E1ciuCvO_all/playlist.m3u8","http_referrer":null,"user_agent":null,"status":"timeout","width":1280,"height":720,"bitrate":1601536,"frame_rate":29.97,"added_at":"2022-08-13T04:41:45Z","updated_at":"2023-01-01T01:33:07Z","checked_at":"2023-01-01T01:33:07Z"},`

requesting to add a tag based on country origin to this like so:

`{"channel":"1001Noites.br","country":"BR", "url":"https://cdn.jmvstream.com/w/LVW-8155/ngrp:LVW8155_41E1ciuCvO_all/playlist.m3u8","http_referrer":null,"user_agent":null,"status":"timeout","width":1280,"height":720,"bitrate":1601536,"frame_rate":29.97,"added_at":"2022-08-13T04:41:45Z","updated_at":"2023-01-01T01:33:07Z","checked_at":"2023-01-01T01:33:07Z"},`

tag "country":"BR" for Brazil, US for USA, etc.

Created a parser of sorts to parse the streams, would like to parse only US results.

Here is the link to my parser: [https://kaos-inc.ga/dev/streams](url)

As you can see, they are output for use with a Kodi addon I'm overhauling, the named channels are sorted and counted on the left and the unnamed channels are sorted/counted on the right.

**Comment by freearhey** [comment]
I don't think that's necessary since you can always get this information from [channels.json](https://github.com/iptv-org/api#channels) by channel ID or just use the ID itself, which already contains the country code (1001Noites.**br**/CNN.**us**).
