### ISSUE TITLE
IPTV-Org parser

### ISSUE THREAD

**Issue by Deadlineem** [iptv-org/api#9]
I took notice that while there are nearly 10,000 channels/playlists, alot of them do not work.  

I've been tinkering with automated ways to parse such things using my own parser im creating in php

https://kaos-inc.ga/dev/IPTV-Org%20Stations%20Parser

This page accomplishes the following automatically on load:

1. Parses the json from the api *streams.json*
2. Gives each Playlist/Channel a Channel Number (Automatically, if iptv-org list updates, this page does, too.)
3. Displays the outputs in the corresponding areas AND formats each channel for use in Kodi using this format:  
        {"title":"CH (channel number). (Channel Name)", "url":"(channel URL)", "image":"None"}

The _**TOP left**_ side is a list of all **Named M3U8 Channels** 
The _**TOP right**_ side is a list of all the **UnNamed M3U8 Channels**
//------//------//------//------//------//------//------//------//------//------//------//------//
The _**BOTTOM left**_ side is a list of all **Named Non-M3U8 channels**
The _**BOTTOM right**_ side is a list of all **UnNamed Non-M3U8 channels**
         
It also lets you one-click copy each content area individually, 8000+ lines of channels would be kind of annoying to manually select/copy, right?

The parser does not currently filter the unworking channels yet, but I plan to add that feature into it.  I was messing around with that on another script but the method i used is flawed because it only filters a maximum of 200 results, out of nearly 10,000.

**Comment by freearhey** [comment]
To let more people know about your project you'd better post a link to it here: https://github.com/iptv-org/awesome-iptv
